# Generated by Django 5.1.1 on 2024-10-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.farmer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.processor'),
        ),
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.farmer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.product'),
        ),
        migrations.AddField(
            model_name='service',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.processor'),
        ),
        migrations.AddField(
            model_name='product',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='products', to='processing.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.service'),
        ),
    ]
