# Generated by Django 5.1.1 on 2024-10-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer',
        ),
    ]
