# Generated by Django 5.1.1 on 2024-10-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_remove_product_farmer'),
        ('user_app', '0004_remove_farmer_products_remove_processor_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='services',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='processor',
        ),
        migrations.AddField(
            model_name='booking',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_services', to='user_app.processor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_services', to='processing.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_services', to='processing.service')),
            ],
            options={
                'unique_together': {('product', 'service', 'processor')},
            },
        ),
    ]
