# Generated by Django 5.1.1 on 2024-10-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_remove_product_price_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
