# Generated by Django 5.1.1 on 2024-10-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_farmer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='products',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='products',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='services',
        ),
    ]
