# Generated by Django 5.1.1 on 2024-10-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
